chore: add .idea to .gitignore
googleapis/google-cloud-ruby pull request #11614
Opened 2021-05-19 07:50 UTC by olavloite

Ignore the .idea directory as it contains local configuration files generated by RubyMine.

2021-05-19 07:56 UTC, hengfengli approved these changes

2021-05-19 15:25 UTC, dazuma requested changes
We might as well make this change to the top level `.gitignore` at the root of the repository, rather than the one specifically in this directory.

2021-05-20 14:54 UTC, dazuma approved these changes

2021-05-20 14:54 UTC, merged

2021-05-20 14:55 UTC, dazuma commented
Thanks!