feat(kms): add samples for new KMS RNG APIs
googleapis/google-cloud-ruby pull request #13604
Opened 2021-08-16 22:45 UTC by sethvargo

This is based on https://github.com/googleapis/google-cloud-ruby/pull/13603 (I'll rebase once that's merged). Unfortunately the tests won't run or pass without it.

This adds new samples for the Cloud KMS RNG APIs.

2021-08-17 19:48 UTC, dazuma commented
@sethvargo  #13603 is merged.

2021-08-17 20:01 UTC, sethvargo commented
@dazuma cool rebased.

2021-08-17 20:25 UTC, dazuma commented
```
  1) Error:
Cloud KMS samples#test_0033_verify_mac:
Google::Cloud::NotFoundError: 5:CryptoKey projects/helical-zone-771/locations/us-east1/keyRings/google-cloud-ruby-samples-key-ring-2/cryptoKeys/google-cloud-ruby-samples-mac_key not found.. debug_error_string:{"created":"@1629230626.086724474","description":"Error received from peer ipv4:74.125.195.95:443","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"CryptoKey projects/helical-zone-771/locations/us-east1/keyRings/google-cloud-ruby-samples-key-ring-2/cryptoKeys/google-cloud-ruby-samples-mac_key not found.","grpc_status":5}
    /h/.gem/gems/google-cloud-kms-v1-0.7.0/lib/google/cloud/kms/v1/key_management_service/client.rb:2242:in `rescue in mac_sign'
    /h/.gem/gems/google-cloud-kms-v1-0.7.0/lib/google/cloud/kms/v1/key_management_service/client.rb:2206:in `mac_sign'
    /workspace/google-cloud-kms/samples/acceptance/snippets_test.rb:647:in `block (2 levels) in <top (required)>'

  2) Error:
Cloud KMS samples#test_0025_sign_mac:
Google::Cloud::NotFoundError: 5:CryptoKey projects/helical-zone-771/locations/us-east1/keyRings/google-cloud-ruby-samples-key-ring-2/cryptoKeys/google-cloud-ruby-samples-mac_key not found.. debug_error_string:{"created":"@1629230627.685743756","description":"Error received from peer ipv4:142.250.99.95:443","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"CryptoKey projects/helical-zone-771/locations/us-east1/keyRings/google-cloud-ruby-samples-key-ring-2/cryptoKeys/google-cloud-ruby-samples-mac_key not found.","grpc_status":5}
    /h/.gem/gems/google-cloud-kms-v1-0.7.0/lib/google/cloud/kms/v1/key_management_service/client.rb:2242:in `rescue in mac_sign'
    /h/.gem/gems/google-cloud-kms-v1-0.7.0/lib/google/cloud/kms/v1/key_management_service/client.rb:2206:in `mac_sign'
    /workspace/google-cloud-kms/samples/snippets.rb:934:in `sign_mac'
    /workspace/google-cloud-kms/samples/acceptance/snippets_test.rb:488:in `block (3 levels) in <top (required)>'
```

2021-08-17 20:42 UTC, sethvargo commented
Someone with permissions on the samples project will need to run `rake fixtures:create`

2021-08-17 20:49 UTC, dazuma commented
> Someone with permissions on the samples project will need to run `rake fixtures:create`

Done. Rerunning tests.

2021-08-17 23:27 UTC, dazuma requested changes

2021-08-17 23:27 UTC, dazuma commented on google-cloud-kms/samples/snippets.rb
> +    sign_response
Should be `verify_response`

2021-08-17 23:49 UTC, sethvargo commented on google-cloud-kms/samples/snippets.rb
> +    sign_response
Fixed

2021-08-18 00:16 UTC, dazuma approved these changes

2021-08-18 00:17 UTC, merged