Update storage_download_file.rb
googleapis/google-cloud-ruby pull request #16189
Opened 2021-12-14 23:17 UTC by rebecca-pete

@frankyn
As currently written, the sample makes a separate request to retrieve bucket metadata. This behavior would require unnecessary, additional IAM permissions.

Also, does line 32 (`file.download`) make a separate request to the API? Is this necessary? Can `file.download` be made `file_download`? Thanks!

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-cloud-ruby/issues) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea.
- [ ] Follow the instructions in [CONTRIBUTING](CONTRIBUTING.md). Most importantly, ensure the tests and linter pass by running `bundle exec rake ci` in the gem subdirectory.
- [ ] Update code documentation if necessary.

closes: #<issue_number_goes_here>

2021-12-14 23:47 UTC, dazuma requested changes

2021-12-14 23:47 UTC, dazuma commented on google-cloud-storage/samples/storage_download_file.rb
> +  puts "Downloaded #{file_name} to #{local_file_path}"
Please revert to `file.name`.

2021-12-14 23:48 UTC, dazuma commented
@rebecca-pete Also, feel free to open a single PR with all the needed sample changes. It may be tedious to open separate PRs if there are a number of changes.

2022-01-13 19:20 UTC, frankyn approved these changes

2022-01-13 19:45 UTC, dazuma approved these changes

2022-01-13 19:46 UTC, merged