samples(pubsub): add sample for eos subscription with ack results
googleapis/google-cloud-ruby pull request #18836
Opened 2022-07-15 05:28 UTC by NivedhaSenthil

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-cloud-ruby/issues) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea.
- [ ] Follow the instructions in [CONTRIBUTING](CONTRIBUTING.md). Most importantly, ensure the tests and linter pass by running `bundle exec rake ci` in the gem subdirectory.
- [ ] Update code documentation if necessary.

closes: #<issue_number_goes_here>

2022-07-15 05:30 UTC, NivedhaSenthil commented
To be merged after https://github.com/googleapis/google-cloud-ruby/pull/18702 and https://github.com/googleapis/google-cloud-ruby/pull/18824

2022-07-28 01:12 UTC, dazuma requested changes

2022-07-28 08:57 UTC, NivedhaSenthil commented on google-cloud-pubsub/samples/pubsub_subscriber_exactly_once.rb
> +# [END pubsub_subscriber_exactly_once]
I tried following the samples guide that we created recently.. https://github.com/GoogleCloudPlatform/samples-style-guide/pull/33/files where we wanted to have the sample being easily runnable with very minimal changes.

2022-07-28 22:16 UTC, dazuma approved these changes
LGTM

2022-07-28 22:16 UTC, dazuma commented on google-cloud-pubsub/samples/pubsub_subscriber_exactly_once.rb
> +# [END pubsub_subscriber_exactly_once]
Oh geez. That style guide needs to be revisited. Having `if $PROGRAM_NAME == __FILE__` boilerplate visible in a sample is just ridiculous.

2022-08-01 00:56 UTC, merged