feat(bigquery): Added support for authorized dataset
googleapis/google-cloud-ruby pull request #19442
Opened 2022-11-16 11:38 UTC by diptanshumittal

2022-12-08 14:14 UTC, bajajneha27 requested changes

2022-12-08 14:14 UTC, bajajneha27 commented on google-cloud-bigquery/acceptance/bigquery/dataset_access_test.rb
> +    dataset = bigquery.dataset dataset_id
Can we use the `reload!` method instead?

2022-12-08 14:14 UTC, bajajneha27 commented on google-cloud-bigquery/acceptance/bigquery/dataset_access_test.rb
> +  it "adds an access entry with specifying dataset hash" do
Nit: adds and removes

2022-12-08 14:14 UTC, bajajneha27 commented on google-cloud-bigquery/lib/google/cloud/bigquery/dataset/access.rb
> +          # @private
Let's add a description of what this dos.

2023-01-12 00:34 UTC, dazuma approved these changes

2023-01-12 17:23 UTC, merged