Upgrading ruby to ruby 3
googleapis/google-cloud-ruby pull request #27599
Opened 2024-11-12 12:44 UTC by shubhangi-google

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-cloud-ruby/issues) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea.
- [ ] Follow the instructions in [CONTRIBUTING](CONTRIBUTING.md). Most importantly, ensure the tests and linter pass by running `bundle exec rake ci` in the gem subdirectory.
- [ ] Update code documentation if necessary.

closes: #<issue_number_goes_here>

2024-11-15 07:44 UTC, bajajneha27 approved these changes
LGTM from my end.

2024-11-21 01:25 UTC, dazuma requested changes

2024-11-21 01:25 UTC, dazuma commented on google-cloud-storage/lib/google/cloud/storage/version.rb
> -      VERSION = "1.52.0".freeze
Please do not update the version manually. This is read and updated during the release process, and modifying it manually will confuse the releaser.

2024-11-21 01:25 UTC, dazuma commented on google-cloud-storage/README.md
>  by Ruby Core—that is, Ruby versions that are either in normal maintenance or in
You'll need to update the following line as well, as it references Ruby 2.5.

2024-11-29 09:57 UTC, bajajneha27 approved these changes

2024-12-04 12:41 UTC, bajajneha27 commented
@dazuma Shivangi has made the changes requested. Can you please take a look?

2024-12-05 21:54 UTC, dazuma approved these changes
Looks good, thanks!

2024-12-05 21:56 UTC, merged