feat(bigtable): Add support for Backup restore to different Instance
googleapis/google-cloud-ruby pull request #8928
Opened 2021-01-18 22:43 UTC by quartzmo

* Add `instance` to `Backup#restore`

closes: #8927

2021-01-18 22:44 UTC, quartzmo commented on google-cloud-bigtable/acceptance/bigtable/backup_test.rb
> +      restore_job = backup.restore restore_table_id, instance: instance_2
Currently failing here using Ruby CI project:

```
  1) Error:
Google::Cloud::Bigtable::Table::bigtable#test_0001_creates a backup:
Google::Cloud::InvalidArgumentError: 3:Request contains an invalid argument.. debug_error_string:{"created":"@1611009167.366622000","description":"Error received from peer ipv4:142.250.68.74:443","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"Request contains an invalid argument.","grpc_status":3}
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin/client.rb:1767:in `rescue in restore_table'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable-admin-v2/lib/google/cloud/bigtable/admin/v2/bigtable_table_admin/client.rb:1732:in `restore_table'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/service.rb:768:in `restore_table'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/backup.rb:386:in `restore'
    /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/acceptance/bigtable/backup_test.rb:128:in `block (2 levels) in <top (required)>'
```

2021-01-26 22:27 UTC, quartzmo commented on google-cloud-bigtable/acceptance/bigtable/backup_test.rb
> +      restore_job = backup.restore restore_table_id, instance: instance_2
This acceptance test is now passing with the google-cloud-ruby CI project and my dev project.

2021-01-26 22:37 UTC, quartzmo commented
This PR is ready for review.

2021-01-26 23:34 UTC, dazuma approved these changes
LGTM

2021-02-02 22:06 UTC, kolea2 commented
Thanks @quartzmo! For now, can you please change the branch it is targeting from master to a different one (ie `backups-restore-instance` or something similar?) Thanks!

2021-02-02 22:07 UTC, kolea2 requested changes
please switch branch, lgtm otherwise

2021-02-02 22:35 UTC, quartzmo commented
@kolea2 OK, this PR is now targeting `backups-restore-instance`, which is a new branch off of `master`.

2021-02-03 00:23 UTC, kolea2 approved these changes

2021-02-03 17:46 UTC, quartzmo commented
@kolea2 What is the schedule for merging this change into master and releasing? Will you notify via this PR?

2021-02-03 18:42 UTC, merged

2021-03-16 18:24 UTC, quartzmo commented
This PR was merged into the topic branch `backups-restore-instance`. It was not merged into `master` branch.

2021-05-03 15:59 UTC, quartzmo commented
This was released in [google-cloud-bigtable v2.6.0](https://rubygems.org/gems/google-cloud-bigtable/versions/2.6.0).